/**
 * This file has no copyright assigned and is placed in the Public Domain.
 * This file is part of the mingw-w64 runtime package.
 * No warranty is given; refer to the file DISCLAIMER.PD within this package.
 */
#ifndef WSABASEERR
# define WSABASEERR                  10000
# define WSAEINTR                    (WSABASEERR + 4)
# define WSAEBADF                    (WSABASEERR + 9)
# define WSAEACCES                   (WSABASEERR + 13)
# define WSAEFAULT                   (WSABASEERR + 14)
# define WSAEINVAL                   (WSABASEERR + 22)
# define WSAEMFILE                   (WSABASEERR + 24)
# define WSAEWOULDBLOCK              (WSABASEERR + 35)
# define WSAEINPROGRESS              (WSABASEERR + 36)
# define WSAEALREADY                 (WSABASEERR + 37)
# define WSAENOTSOCK                 (WSABASEERR + 38)
# define WSAEDESTADDRREQ             (WSABASEERR + 39)
# define WSAEMSGSIZE                 (WSABASEERR + 40)
# define WSAEPROTOTYPE               (WSABASEERR + 41)
# define WSAENOPROTOOPT              (WSABASEERR + 42)
# define WSAEPROTONOSUPPORT          (WSABASEERR + 43)
# define WSAESOCKTNOSUPPORT          (WSABASEERR + 44)
# define WSAEOPNOTSUPP               (WSABASEERR + 45)
# define WSAEPFNOSUPPORT             (WSABASEERR + 46)
# define WSAEAFNOSUPPORT             (WSABASEERR + 47)
# define WSAEADDRINUSE               (WSABASEERR + 48)
# define WSAEADDRNOTAVAIL            (WSABASEERR + 49)
# define WSAENETDOWN                 (WSABASEERR + 50)
# define WSAENETUNREACH              (WSABASEERR + 51)
# define WSAENETRESET                (WSABASEERR + 52)
# define WSAECONNABORTED             (WSABASEERR + 53)
# define WSAECONNRESET               (WSABASEERR + 54)
# define WSAENOBUFS                  (WSABASEERR + 55)
# define WSAEISCONN                  (WSABASEERR + 56)
# define WSAENOTCONN                 (WSABASEERR + 57)
# define WSAESHUTDOWN                (WSABASEERR + 58)
# define WSAETOOMANYREFS             (WSABASEERR + 59)
# define WSAETIMEDOUT                (WSABASEERR + 60)
# define WSAECONNREFUSED             (WSABASEERR + 61)
# define WSAELOOP                    (WSABASEERR + 62)
# define WSAENAMETOOLONG             (WSABASEERR + 63)
# define WSAEHOSTDOWN                (WSABASEERR + 64)
# define WSAEHOSTUNREACH             (WSABASEERR + 65)
# define WSAENOTEMPTY                (WSABASEERR + 66)
# define WSAEPROCLIM                 (WSABASEERR + 67)
# define WSAEUSERS                   (WSABASEERR + 68)
# define WSAEDQUOT                   (WSABASEERR + 69)
# define WSAESTALE                   (WSABASEERR + 70)
# define WSAEREMOTE                  (WSABASEERR + 71)
# define WSAEDISCON                  (WSABASEERR + 101)
# define WSASYSNOTREADY              (WSABASEERR + 91)
# define WSAVERNOTSUPPORTED          (WSABASEERR + 92)
# define WSANOTINITIALISED           (WSABASEERR + 93)
# define WSAHOST_NOT_FOUND           (WSABASEERR + 1001)
# define WSATRY_AGAIN                (WSABASEERR + 1002)
# define WSANO_RECOVERY              (WSABASEERR + 1003)
# define WSANO_DATA                  (WSABASEERR + 1004)
# define WSA_SECURE_HOST_NOT_FOUND   (WSABASEERR + 1032)
# define WSA_IPSEC_NAME_POLICY_ERROR (WSABASEERR + 1033)
# ifdef _WINSOCK2API_
#   define WSAENOMORE                 (WSABASEERR + 102)
#   define WSAECANCELLED              (WSABASEERR + 103)
#   define WSAEINVALIDPROCTABLE       (WSABASEERR + 104)
#   define WSAEINVALIDPROVIDER        (WSABASEERR + 105)
#   define WSAEPROVIDERFAILEDINIT     (WSABASEERR + 106)
#   define WSASYSCALLFAILURE          (WSABASEERR + 107)
#   define WSASERVICE_NOT_FOUND       (WSABASEERR + 108)
#   define WSATYPE_NOT_FOUND          (WSABASEERR + 109)
#   define WSA_E_NO_MORE              (WSABASEERR + 110)
#   define WSA_E_CANCELLED            (WSABASEERR + 111)
#   define WSAEREFUSED                (WSABASEERR + 112)
#   define WSA_QOS_RECEIVERS          (WSABASEERR + 1005)
#   define WSA_QOS_SENDERS            (WSABASEERR + 1006)
#   define WSA_QOS_NO_SENDERS         (WSABASEERR + 1007)
#   define WSA_QOS_NO_RECEIVERS       (WSABASEERR + 1008)
#   define WSA_QOS_REQUEST_CONFIRMED  (WSABASEERR + 1009)
#   define WSA_QOS_ADMISSION_FAILURE  (WSABASEERR + 1010)
#   define WSA_QOS_POLICY_FAILURE     (WSABASEERR + 1011)
#   define WSA_QOS_BAD_STYLE          (WSABASEERR + 1012)
#   define WSA_QOS_BAD_OBJECT         (WSABASEERR + 1013)
#   define WSA_QOS_TRAFFIC_CTRL_ERROR (WSABASEERR + 1014)
#   define WSA_QOS_GENERIC_ERROR      (WSABASEERR + 1015)
#   define WSA_QOS_ESERVICETYPE       (WSABASEERR + 1016)
#   define WSA_QOS_EFLOWSPEC          (WSABASEERR + 1017)
#   define WSA_QOS_EPROVSPECBUF       (WSABASEERR + 1018)
#   define WSA_QOS_EFILTERSTYLE       (WSABASEERR + 1019)
#   define WSA_QOS_EFILTERTYPE        (WSABASEERR + 1020)
#   define WSA_QOS_EFILTERCOUNT       (WSABASEERR + 1021)
#   define WSA_QOS_EOBJLENGTH         (WSABASEERR + 1022)
#   define WSA_QOS_EFLOWCOUNT         (WSABASEERR + 1023)
#   define WSA_QOS_EUNKOWNPSOBJ       (WSABASEERR + 1024)
#   define WSA_QOS_EPOLICYOBJ         (WSABASEERR + 1025)
#   define WSA_QOS_EFLOWDESC          (WSABASEERR + 1026)
#   define WSA_QOS_EPSFLOWSPEC        (WSABASEERR + 1027)
#   define WSA_QOS_EPSFILTERSPEC      (WSABASEERR + 1028)
#   define WSA_QOS_ESDMODEOBJ         (WSABASEERR + 1029)
#   define WSA_QOS_ESHAPERATEOBJ      (WSABASEERR + 1030)
#   define WSA_QOS_RESERVED_PETYPE    (WSABASEERR + 1031)
# endif  /* _WINSOCK2API_ */
#endif  /* WSABASEERR */

#ifndef __WSA_ERR_MACROS_DEFINED
# define __WSA_ERR_MACROS_DEFINED
# define h_errno         WSAGetLastError()
# define HOST_NOT_FOUND  WSAHOST_NOT_FOUND
# define TRY_AGAIN       WSATRY_AGAIN
# define NO_RECOVERY     WSANO_RECOVERY
# define NO_DATA         WSANO_DATA
# define WSANO_ADDRESS   WSANO_DATA
# define NO_ADDRESS      WSANO_ADDRESS
#endif  /* __WSA_ERR_MACROS_DEFINED */
