libarm64_DATA += %reldir%/libaclui.a
libarm64_DATA += %reldir%/libactiveds.a
#libarm64_DATA += %reldir%/libadsiid.a  # Handled by custom rule
libarm64_DATA += %reldir%/libadvapi32.a
libarm64_DATA += %reldir%/libadvpack.a
libarm64_DATA += %reldir%/libamsi.a
#libarm64_DATA += %reldir%/libamstrmid.a  # Handled by custom rule
libarm64_DATA += %reldir%/libappmgmts.a
libarm64_DATA += %reldir%/libappnotify.a
libarm64_DATA += %reldir%/libaudioeng.a
libarm64_DATA += %reldir%/libauthz.a
libarm64_DATA += %reldir%/libavifil32.a
libarm64_DATA += %reldir%/libavrt.a
libarm64_DATA += %reldir%/libbasesrv.a
libarm64_DATA += %reldir%/libbcp47mrm.a
libarm64_DATA += %reldir%/libbcrypt.a
libarm64_DATA += %reldir%/libbindlink.a
#libarm64_DATA += %reldir%/libbits.a  # Handled by custom rule
libarm64_DATA += %reldir%/libbluetoothapis.a
libarm64_DATA += %reldir%/libbthprops.a
libarm64_DATA += %reldir%/libcabinet.a
libarm64_DATA += %reldir%/libcertadm.a
libarm64_DATA += %reldir%/libcertcli.a
libarm64_DATA += %reldir%/libcertpoleng.a
libarm64_DATA += %reldir%/libcfgmgr32.a
libarm64_DATA += %reldir%/libchakrart.a
libarm64_DATA += %reldir%/libcimfs.a
libarm64_DATA += %reldir%/libcldapi.a
libarm64_DATA += %reldir%/libclfsw32.a
libarm64_DATA += %reldir%/libclusapi.a
libarm64_DATA += %reldir%/libcomctl32.a
libarm64_DATA += %reldir%/libcomdlg32.a
libarm64_DATA += %reldir%/libcomppkgsup.a
libarm64_DATA += %reldir%/libcompstui.a
libarm64_DATA += %reldir%/libcomputecore.a
libarm64_DATA += %reldir%/libcomputenetwork.a
libarm64_DATA += %reldir%/libcomputestorage.a
libarm64_DATA += %reldir%/libcomsvcs.a
libarm64_DATA += %reldir%/libcoremessaging.a
libarm64_DATA += %reldir%/libcredui.a
libarm64_DATA += %reldir%/libcrypt32.a
libarm64_DATA += %reldir%/libcryptdll.a
libarm64_DATA += %reldir%/libcryptnet.a
libarm64_DATA += %reldir%/libcryptui.a
libarm64_DATA += %reldir%/libcryptxml.a
libarm64_DATA += %reldir%/libcscapi.a
libarm64_DATA += %reldir%/libcscdll.a
libarm64_DATA += %reldir%/libd2d1.a
libarm64_DATA += %reldir%/libd3d10.a
libarm64_DATA += %reldir%/libd3d10_1.a
libarm64_DATA += %reldir%/libd3d11.a
libarm64_DATA += %reldir%/libd3d12.a
libarm64_DATA += %reldir%/libd3d9.a
libarm64_DATA += %reldir%/libd3dcompiler.a
libarm64_DATA += %reldir%/libdavclnt.a
libarm64_DATA += %reldir%/libdbgeng.a
libarm64_DATA += %reldir%/libdbghelp.a
libarm64_DATA += %reldir%/libdbgmodel.a
libarm64_DATA += %reldir%/libdcomp.a
libarm64_DATA += %reldir%/libddraw.a
libarm64_DATA += %reldir%/libdeviceaccess.a
libarm64_DATA += %reldir%/libdevmgr.a
libarm64_DATA += %reldir%/libdflayout.a
libarm64_DATA += %reldir%/libdhcpcsvc.a
libarm64_DATA += %reldir%/libdhcpcsvc6.a
libarm64_DATA += %reldir%/libdhcpsapi.a
libarm64_DATA += %reldir%/libdiagnosticdataquery.a
#libarm64_DATA += %reldir%/libdinput8.a  # Handled by custom rule
libarm64_DATA += %reldir%/libdirectml.a
#libarm64_DATA += %reldir%/libdloadhelper.a  # Handled by custom rule
#libarm64_DATA += %reldir%/libdmoguids.a  # Handled by custom rule
libarm64_DATA += %reldir%/libdmprocessxmlfiltered.a
libarm64_DATA += %reldir%/libdnsapi.a
libarm64_DATA += %reldir%/libdnsperf.a
libarm64_DATA += %reldir%/libdnsrslvr.a
libarm64_DATA += %reldir%/libdpx.a
libarm64_DATA += %reldir%/libdsound.a
libarm64_DATA += %reldir%/libdsprop.a
libarm64_DATA += %reldir%/libdssec.a
libarm64_DATA += %reldir%/libdststlog.a
libarm64_DATA += %reldir%/libdsuiext.a
libarm64_DATA += %reldir%/libdwmapi.a
libarm64_DATA += %reldir%/libdwrite.a
libarm64_DATA += %reldir%/libdxcompiler.a
libarm64_DATA += %reldir%/libdxcore.a
libarm64_DATA += %reldir%/libdxgi.a
#libarm64_DATA += %reldir%/libdxguid.a  # Handled by custom rule
libarm64_DATA += %reldir%/libdxva2.a
libarm64_DATA += %reldir%/libeappcfg.a
libarm64_DATA += %reldir%/libeappprxy.a
libarm64_DATA += %reldir%/libefswrt.a
libarm64_DATA += %reldir%/libelscore.a
libarm64_DATA += %reldir%/libesent.a
libarm64_DATA += %reldir%/libevr.a
libarm64_DATA += %reldir%/libfaultrep.a
libarm64_DATA += %reldir%/libfeclient.a
libarm64_DATA += %reldir%/libfhsvcctl.a
libarm64_DATA += %reldir%/libfltlib.a
libarm64_DATA += %reldir%/libfontsub.a
libarm64_DATA += %reldir%/libframedyn.a
libarm64_DATA += %reldir%/libfwpuclnt.a
libarm64_DATA += %reldir%/libgameinput.a
libarm64_DATA += %reldir%/libgdi32.a
#libarm64_DATA += %reldir%/libgdiplus.a  # Handled by custom rule
libarm64_DATA += %reldir%/libglmf32.a
libarm64_DATA += %reldir%/libglu32.a
libarm64_DATA += %reldir%/libgpedit.a
libarm64_DATA += %reldir%/libhbaapi.a
libarm64_DATA += %reldir%/libhhsetup.a
libarm64_DATA += %reldir%/libhid.a
libarm64_DATA += %reldir%/libhlink.a
libarm64_DATA += %reldir%/libhrtfapo.a
libarm64_DATA += %reldir%/libhtmlhelp.a
libarm64_DATA += %reldir%/libhttpapi.a
libarm64_DATA += %reldir%/libhwreqchk.a
libarm64_DATA += %reldir%/libiashlpr.a
libarm64_DATA += %reldir%/libicm32.a
libarm64_DATA += %reldir%/libicmui.a
libarm64_DATA += %reldir%/libicu.a
libarm64_DATA += %reldir%/libicuin.a
libarm64_DATA += %reldir%/libicuuc.a
libarm64_DATA += %reldir%/libiepmapi.a
libarm64_DATA += %reldir%/libiesetup.a
libarm64_DATA += %reldir%/libimagehlp.a
libarm64_DATA += %reldir%/libimgutil.a
libarm64_DATA += %reldir%/libimm32.a
libarm64_DATA += %reldir%/libinkobjcore.a
libarm64_DATA += %reldir%/libinseng.a
libarm64_DATA += %reldir%/libiphlpapi.a
libarm64_DATA += %reldir%/libiprop.a
libarm64_DATA += %reldir%/libiscsidsc.a
libarm64_DATA += %reldir%/libjsrt.a
#libarm64_DATA += %reldir%/libkernel32.a  # Handled by custom rule
libarm64_DATA += %reldir%/libkeycredmgr.a
libarm64_DATA += %reldir%/libksproxy.a
#libarm64_DATA += %reldir%/libksuser.a  # Handled by custom rule
libarm64_DATA += %reldir%/libktmw32.a
libarm64_DATA += %reldir%/liblamparray.a
libarm64_DATA += %reldir%/liblicenseprotection.a
libarm64_DATA += %reldir%/libloadperf.a
#libarm64_DATA += %reldir%/liblocationapi.a  # Handled by custom rule
libarm64_DATA += %reldir%/liblz32.a
libarm64_DATA += %reldir%/libmagnification.a
libarm64_DATA += %reldir%/libmapi32.a
libarm64_DATA += %reldir%/libmciole32.a
libarm64_DATA += %reldir%/libmdmlocalmanagement.a
libarm64_DATA += %reldir%/libmdmregistration.a
libarm64_DATA += %reldir%/libmf.a
libarm64_DATA += %reldir%/libmfcore.a
libarm64_DATA += %reldir%/libmfplat.a
libarm64_DATA += %reldir%/libmfplay.a
libarm64_DATA += %reldir%/libmfreadwrite.a
libarm64_DATA += %reldir%/libmfsensorgroup.a
libarm64_DATA += %reldir%/libmfsrcsnk.a
#libarm64_DATA += %reldir%/libmfuuid.a  # Handled by custom rule
libarm64_DATA += %reldir%/libmgmtapi.a
libarm64_DATA += %reldir%/libmi.a
libarm64_DATA += %reldir%/libmincore.a
libarm64_DATA += %reldir%/libmmdevapi.a
libarm64_DATA += %reldir%/libmmos.a
libarm64_DATA += %reldir%/libmpr.a
libarm64_DATA += %reldir%/libmprapi.a
libarm64_DATA += %reldir%/libmprsnap.a
libarm64_DATA += %reldir%/libmsacm32.a
libarm64_DATA += %reldir%/libmscms.a
libarm64_DATA += %reldir%/libmsctfmonitor.a
libarm64_DATA += %reldir%/libmsdelta.a
libarm64_DATA += %reldir%/libmsdmo.a
libarm64_DATA += %reldir%/libmsdrm.a
libarm64_DATA += %reldir%/libmsi.a
libarm64_DATA += %reldir%/libmsimg32.a
libarm64_DATA += %reldir%/libmspatcha.a
libarm64_DATA += %reldir%/libmspatchc.a
libarm64_DATA += %reldir%/libmsports.a
libarm64_DATA += %reldir%/libmsrating.a
libarm64_DATA += %reldir%/libmstask.a
libarm64_DATA += %reldir%/libmsv1_0.a
libarm64_DATA += %reldir%/libmsvfw32.a
libarm64_DATA += %reldir%/libmswsock.a
#libarm64_DATA += %reldir%/libmsxml2.a  # Handled by custom rule
#libarm64_DATA += %reldir%/libmsxml6.a  # Handled by custom rule
libarm64_DATA += %reldir%/libmtx.a
libarm64_DATA += %reldir%/libmtxdm.a
libarm64_DATA += %reldir%/libncrypt.a
libarm64_DATA += %reldir%/libnddeapi.a
libarm64_DATA += %reldir%/libndfapi.a
libarm64_DATA += %reldir%/libnetapi32.a
libarm64_DATA += %reldir%/libnetsh.a
libarm64_DATA += %reldir%/libnewdev.a
libarm64_DATA += %reldir%/libninput.a
libarm64_DATA += %reldir%/libnormaliz.a
libarm64_DATA += %reldir%/libntdll.a
libarm64_DATA += %reldir%/libntdllp.a
libarm64_DATA += %reldir%/libntdsa.a
libarm64_DATA += %reldir%/libntdsapi.a
libarm64_DATA += %reldir%/libntdsatq.a
libarm64_DATA += %reldir%/libntdsetup.a
libarm64_DATA += %reldir%/libntfrsapi.a
libarm64_DATA += %reldir%/libntlanman.a
libarm64_DATA += %reldir%/libntmarta.a
libarm64_DATA += %reldir%/libntquery.a
libarm64_DATA += %reldir%/libodbc32.a
libarm64_DATA += %reldir%/libodbcbcp.a
libarm64_DATA += %reldir%/libodbccp32.a
libarm64_DATA += %reldir%/liboemlicense.a
libarm64_DATA += %reldir%/libole32.a
libarm64_DATA += %reldir%/liboleacc.a
libarm64_DATA += %reldir%/liboleaut32.a
libarm64_DATA += %reldir%/libolecli32.a
libarm64_DATA += %reldir%/liboledlg.a
libarm64_DATA += %reldir%/libolesvr32.a
libarm64_DATA += %reldir%/libondemandconnroutehelper.a
libarm64_DATA += %reldir%/libonecoreuap_apiset.a
libarm64_DATA += %reldir%/libonecore_apiset.a
libarm64_DATA += %reldir%/libopengl32.a
libarm64_DATA += %reldir%/libpathcch.a
libarm64_DATA += %reldir%/libpdh.a
libarm64_DATA += %reldir%/libpeerdist.a
#libarm64_DATA += %reldir%/libportabledeviceguids.a  # Handled by custom rule
libarm64_DATA += %reldir%/libpowrprof.a
libarm64_DATA += %reldir%/libprntvpt.a
libarm64_DATA += %reldir%/libprojectedfslib.a
libarm64_DATA += %reldir%/libpropsys.a
libarm64_DATA += %reldir%/libpsapi.a
libarm64_DATA += %reldir%/libquartz.a
libarm64_DATA += %reldir%/libquery.a
libarm64_DATA += %reldir%/libqwave.a
libarm64_DATA += %reldir%/librasapi32.a
libarm64_DATA += %reldir%/librasdlg.a
libarm64_DATA += %reldir%/librasuser.a
libarm64_DATA += %reldir%/libresutils.a
libarm64_DATA += %reldir%/librilproxy.a
libarm64_DATA += %reldir%/librimapi.a
libarm64_DATA += %reldir%/librometadata.a
libarm64_DATA += %reldir%/librpcexts.a
libarm64_DATA += %reldir%/librpcns4.a
libarm64_DATA += %reldir%/librpcproxy.a
libarm64_DATA += %reldir%/librpcrt4.a
libarm64_DATA += %reldir%/librstrtmgr.a
libarm64_DATA += %reldir%/librtm.a
libarm64_DATA += %reldir%/librtutils.a
libarm64_DATA += %reldir%/librtworkq.a
libarm64_DATA += %reldir%/libruntimeobject.a
libarm64_DATA += %reldir%/libsamlib.a
libarm64_DATA += %reldir%/libsamsrv.a
#libarm64_DATA += %reldir%/libsapi.a  # Handled by custom rule
libarm64_DATA += %reldir%/libsas.a
libarm64_DATA += %reldir%/libscarddlg.a
libarm64_DATA += %reldir%/libscecli.a
libarm64_DATA += %reldir%/libscesrv.a
libarm64_DATA += %reldir%/libschannel.a
#libarm64_DATA += %reldir%/libscrnsave.a  # Handled by custom rule
#libarm64_DATA += %reldir%/libscrnsavw.a  # Handled by custom rule
libarm64_DATA += %reldir%/libsecur32.a
libarm64_DATA += %reldir%/libsecurity.a
libarm64_DATA += %reldir%/libsens.a
libarm64_DATA += %reldir%/libsensapi.a
#libarm64_DATA += %reldir%/libsensorsapi.a  # Handled by custom rule
libarm64_DATA += %reldir%/libsensorsutils.a
libarm64_DATA += %reldir%/libsetupapi.a
libarm64_DATA += %reldir%/libsfc.a
libarm64_DATA += %reldir%/libshcore.a
libarm64_DATA += %reldir%/libshdocvw.a
#libarm64_DATA += %reldir%/libshell32.a  # Handled by custom rule
libarm64_DATA += %reldir%/libshfolder.a
libarm64_DATA += %reldir%/libshlwapi.a
libarm64_DATA += %reldir%/libslc.a
libarm64_DATA += %reldir%/libslcext.a
libarm64_DATA += %reldir%/libslwga.a
libarm64_DATA += %reldir%/libsnmpapi.a
libarm64_DATA += %reldir%/libspoolss.a
libarm64_DATA += %reldir%/libsporder.a
libarm64_DATA += %reldir%/libsrpapi.a
libarm64_DATA += %reldir%/libssdpapi.a
libarm64_DATA += %reldir%/libsti.a
#libarm64_DATA += %reldir%/libstrmiids.a  # Handled by custom rule
libarm64_DATA += %reldir%/libswdevice.a
libarm64_DATA += %reldir%/libsynchronization.a
libarm64_DATA += %reldir%/libt2embed.a
libarm64_DATA += %reldir%/libtapi32.a
#libarm64_DATA += %reldir%/libtaskschd.a  # Handled by custom rule
libarm64_DATA += %reldir%/libtbs.a
libarm64_DATA += %reldir%/libtdh.a
libarm64_DATA += %reldir%/libtokenbinding.a
libarm64_DATA += %reldir%/libtraffic.a
libarm64_DATA += %reldir%/libtsec.a
libarm64_DATA += %reldir%/libtwinapi.a
libarm64_DATA += %reldir%/libtxfw32.a
libarm64_DATA += %reldir%/libualapi.a
libarm64_DATA += %reldir%/libuiautomationcore.a
libarm64_DATA += %reldir%/libumpdddi.a
libarm64_DATA += %reldir%/liburlmon.a
#libarm64_DATA += %reldir%/libucrt.a  # Handled by custom rule
#libarm64_DATA += %reldir%/libucrtapp.a  # Handled by custom rule
#libarm64_DATA += %reldir%/libucrtbase.a  # Handled by custom rule
libarm64_DATA += %reldir%/libusbpmapi.a
libarm64_DATA += %reldir%/libuser32.a
libarm64_DATA += %reldir%/libuserenv.a
libarm64_DATA += %reldir%/libusp10.a
#libarm64_DATA += %reldir%/libuuid.a  # Handled by custom rule
libarm64_DATA += %reldir%/libuxtheme.a
libarm64_DATA += %reldir%/libversion.a
libarm64_DATA += %reldir%/libvertdll.a
libarm64_DATA += %reldir%/libvfw32.a
libarm64_DATA += %reldir%/libvhfum.a
libarm64_DATA += %reldir%/libvirtdisk.a
libarm64_DATA += %reldir%/libvmdevicehost.a
libarm64_DATA += %reldir%/libvssapi.a
#libarm64_DATA += %reldir%/libwbemuuid.a  # Handled by custom rule
libarm64_DATA += %reldir%/libwcmapi.a
libarm64_DATA += %reldir%/libwdsbp.a
libarm64_DATA += %reldir%/libwdsclientapi.a
libarm64_DATA += %reldir%/libwdsmc.a
libarm64_DATA += %reldir%/libwdspxe.a
libarm64_DATA += %reldir%/libwdstptc.a
libarm64_DATA += %reldir%/libwebauthn.a
libarm64_DATA += %reldir%/libwebservices.a
libarm64_DATA += %reldir%/libwebsocket.a
libarm64_DATA += %reldir%/libwecapi.a
libarm64_DATA += %reldir%/libwer.a
libarm64_DATA += %reldir%/libwevtapi.a
libarm64_DATA += %reldir%/libwiaservc.a
libarm64_DATA += %reldir%/libwinbio.a
libarm64_DATA += %reldir%/libwindows.ai.machinelearning.a
libarm64_DATA += %reldir%/libwindows.data.pdf.a
libarm64_DATA += %reldir%/libwindows.media.mediacontrol.a
libarm64_DATA += %reldir%/libwindows.networking.a
libarm64_DATA += %reldir%/libwindows.ui.a
libarm64_DATA += %reldir%/libwindowsapp.a
#libarm64_DATA += %reldir%/libwindowscodecs.a  # Handled by custom rule
libarm64_DATA += %reldir%/libwindowscoreheadless_apiset.a
libarm64_DATA += %reldir%/libwinhttp.a
libarm64_DATA += %reldir%/libwinhvplatform.a
libarm64_DATA += %reldir%/libwininet.a
libarm64_DATA += %reldir%/libwinml.a
libarm64_DATA += %reldir%/libwinmm.a
libarm64_DATA += %reldir%/libwinscard.a
libarm64_DATA += %reldir%/libwinspool.a
libarm64_DATA += %reldir%/libwinsqlite3.a
libarm64_DATA += %reldir%/libwinsta.a
libarm64_DATA += %reldir%/libwintrust.a
libarm64_DATA += %reldir%/libwinusb.a
libarm64_DATA += %reldir%/libwlanapi.a
libarm64_DATA += %reldir%/libwlanui.a
libarm64_DATA += %reldir%/libwldap32.a
libarm64_DATA += %reldir%/libwldp.a
#libarm64_DATA += %reldir%/libwmcodecdspuuid.a  # Handled by custom rule
libarm64_DATA += %reldir%/libwmip.a
libarm64_DATA += %reldir%/libwmvcore.a
libarm64_DATA += %reldir%/libwofutil.a
libarm64_DATA += %reldir%/libwpprecorderum.a
#libarm64_DATA += %reldir%/libws2_32.a  # Handled by custom rule
libarm64_DATA += %reldir%/libwscapi.a
libarm64_DATA += %reldir%/libwsclient.a
libarm64_DATA += %reldir%/libwsdapi.a
libarm64_DATA += %reldir%/libwsmsvc.a
libarm64_DATA += %reldir%/libwsnmp32.a
libarm64_DATA += %reldir%/libwsock32.a
libarm64_DATA += %reldir%/libwtsapi32.a
libarm64_DATA += %reldir%/libxaudio2.a
libarm64_DATA += %reldir%/libxaudio2_8.a
libarm64_DATA += %reldir%/libxinput.a
libarm64_DATA += %reldir%/libxinput9_1_0.a
libarm64_DATA += %reldir%/libxinputuap.a
libarm64_DATA += %reldir%/libxmllite.a
libarm64_DATA += %reldir%/libxolehlp.a
libarm64_DATA += %reldir%/libxpsdocumenttargetprint.a
libarm64_DATA += %reldir%/libxpsprint.a
